exclude_paths:
  - "db/migrate"
  - "bin"
  - "node_modules"
  - "vendor"

detectors:
  InstanceVariableAssumption:
    enabled: false
  IrresponsibleModule:
    enabled: false
  UncommunicativeModuleName:
    exclude:
      - Api::V1
  UncommunicativeVariableName:
    exclude:
      - Api::V1::UsersController#index
      - Api::V1::PostsController#index
